### ISSUE TITLE
Unable to connect to mqtt server

### ISSUE THREAD

**Issue by hpham04** [reap/MQTT-InfluxDB-bridge#6]
I want to experience mqtt, influxdb & grafana so I installed all of them
In order to send data from mqtt server to influxdb, I used this plugin. However, it cannot connect to mqtt server. Below is the log which it printed out. 
Can you please help to advise:
docker run -e BROKER="tcp://localhost:1883" -e DB="http://localhost:8086" reap/mqtt-influxdb-bridge
+ exec app
time="2018-04-11T09:30:36Z" level=info msg="Using broker tcp://localhost:1883"
time="2018-04-11T09:30:36Z" level=info msg="Using database http://localhost:8086"
panic: Network Error : dial tcp 127.0.0.1:1883: getsockopt: connection refused

goroutine 1 [running]:
main.createMQTTClient(0xc42000c067, 0x14, 0xc4200144e0)
	/go/src/app/main.go:111 +0x2a2
main.main()
	/go/src/app/main.go:125 +0x78

I used MQTT fx tool to test and saw that mqtt server is up & running

**Comment by hpham04** [comment]
I changed 'localhost' address to IP (172.17.0.2, 172.17.0.4) then it works

**Comment by reap** [comment]
Good thing that you got it working, sorry that I had not noticed this message earlier.
