### ISSUE TITLE
Unable to write data to influxdb

### ISSUE THREAD

**Issue by hpham04** [reap/MQTT-InfluxDB-bridge#7]
I tried to push message into mqtt queue, below is the log of this bridge:
docker run  -e DB="http://172.17.0.2:8086" -e BROKER="tcp://172.17.0.4:1883" reap/mqtt-influxdb-bridge
+ exec app
time="2018-04-11T10:23:40Z" level=info msg="Using broker tcp://172.17.0.4:1883"
time="2018-04-11T10:23:40Z" level=info msg="Using database http://172.17.0.2:8086"
time="2018-04-11T10:23:40Z" level=info msg="Listener running"
time="2018-04-11T10:23:40Z" level=info msg="Starting listener"
time="2018-04-11T10:23:50Z" level=info msg="Received message" payload=999 topic=/mydb
time="2018-04-11T10:23:50Z" level=fatal msg="{\"error\":\"database is required\"}\n"

Looking into the log of influxdb, it looks like this bridge didn't function correctly:
[httpd] 172.17.0.5 - - [11/Apr/2018:10:21:01 +0000] "POST /write?consistency=&db=&precision=s&rp= HTTP/1.1" 400 33 "-" "InfluxDBClient" 08d6e16f-3d72-11e8-8044-000000000000 80

Note: I tried to use topic like /mydb/room1/temperature and the same error occurred

**Comment by reap** [comment]
There was a problem selecting the items from the mqtt-topic, now the problem should be fixed.
